# manifest:
#   remotes:
#     - name: zmkfirmware
#       url-base: https://github.com/zmkfirmware
#   projects:
#     - name: zmk
#       remote: zmkfirmware
#       revision: main
#       import: app/west.yml
#   self:
#     path: config

manifest:
    remotes:
      - name: zmkfirmware
        url-base: https://github.com/zmkfirmware
      - name: infused-kim
        url-base: https://github.com/infused-kim
      - name: xzebra
        url-base: https://github.com/xzebra
    projects:
      - name: zmk
        remote: xzebra
        revision: split-encoders
        import: app/west.yml
    self:
      path: config
