manifest:
    remotes:
      - name: zmkfirmware
        url-base: https://github.com/zmkfirmware
      - name: xzebra
        url-base: https://github.com/xzebra
    projects:
      - name: zmk
        remote: xzebra
        revision: split-encoders    
        import: app/west.yml
    self:
      path: config
